name: Makefile CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.7.4

    steps:
    - uses: actions/checkout@v2
      
    - name: Build Plugin
      run: make
      
    - name: Upload Plugin
      uses: actions/upload-artifact@v4
      with:
        name: Plugin 3GX File
        path: SMM3DSPlugin.3gx
    
    - name: Upload Plugin ELF
      uses: actions/upload-artifact@v4
      with:
        name: Plugin ELF File
        path: SMM3DSPlugin.elf
